FROM ubuntu:latest
RUN apt update && apt install -y software-properties-common && add-apt-repository ppa:deadsnakes/ppa -y
RUN apt update && apt install -y python3.7 python3-pip python3-venv

CMD sleep 600
